export const categories = [
  {
    id: 1,
    name: "Electronics",
    sku: "ELEC001",
    description: "Gadgets and devices",
    image:
      "https://shorthand.com/the-craft/raster-images/assets/5kVrMqC0wp/sh-unsplash_5qt09yibrok-4096x2731.jpeg",
  },
  {
    id: 2,
    name: "Clothing",
    sku: "CLOTH001",
    description: "Apparel and garments",
    image: "",
  },
  {
    id: 3,
    name: "Footwear",
    sku: "FOOT001",
    description: "Shoes and sandals",
    image: "",
  },
];

export const products = [
  {
    id: 1,
    name: "iPhone 15 Pro",
    category: "Electronics",
    price: "999.00",
    stock: 45,
    status: "Active",
    image:
      "https://image01-in.oneplus.net/media/202406/19/dee6a15ca313f3a7b211f2a440e9f05e.png?x-amz-process=image/format,webp/quality,Q_80",
    rating: 4.8,
  },
  {
    id: 2,
    name: "MacBook Air M2",
    category: "Electronics",
    price: "1,299.00",
    stock: 23,
    status: "Active",
    image: "💻",
    rating: 4.9,
  },
  {
    id: 3,
    name: "Nike Air Max",
    category: "Footwear",
    price: "129.99",
    stock: 0,
    status: "Out of Stock",
    image: "👟",
    rating: 4.6,
  },
  {
    id: 4,
    name: "Sony WH-1000XM5",
    category: "Electronics",
    price: "399.99",
    stock: 67,
    status: "Active",
    image: "🎧",
    rating: 4.7,
  },
  {
    id: 5,
    name: "Levi's Jeans",
    category: "Clothing",
    price: "89.99",
    stock: 156,
    status: "Active",
    image: "👖",
    rating: 4.4,
  },
];

export const orders = [
  {
    id: "#12345",
    customer: "John Doe",
    email: "john@example.com",
    contact: "+1-555-1234",
    total: "125.00",
    status: "Completed",
    payment: "Paid",
    date: "2025-06-19",
    dueDate: "2025-06-19",
    items: 3,
    productName: "Wireless Headphones",
    productImg: "https://image01-in.oneplus.net/media/202406/19/dee6a15ca313f3a7b211f2a440e9f05e.png?x-amz-process=image/format,webp/quality,Q_80",
  },
  {
    id: "#12346",
    customer: "Jane Smith",
    email: "jane@example.com",
    contact: "+1-555-5678",
    total: "89.50",
    status: "Processing",
    payment: "Paid",
    dueDate: "2025-06-19",
    date: "2025-06-19",
    items: 2,
    productName: "Bluetooth Speaker",
    productImg: "https://example.com/images/speaker.jpg",
  },
  {
    id: "#12347",
    customer: "Bob Johnson",
    email: "bob@example.com",
    contact: "+1-555-9012",
    total: "200.75",
    status: "Shipped",
    payment: "Paid",
    dueDate: "2025-06-19",
    date: "2025-06-18",
    items: 5,
    productName: "Smartwatch",
    productImg: "https://example.com/images/smartwatch.jpg",
  },
  {
    id: "#12348",
    customer: "Alice Brown",
    email: "alice@example.com",
    contact: "+1-555-3456",
    total: "156.25",
    status: "Pending",
    payment: "Pending",
    dueDate: "2025-06-19",
    date: "2025-06-18",
    items: 1,
    productName: "Fitness Tracker",
    productImg: "https://example.com/images/tracker.jpg",
  },
  {
    id: "#12349",
    customer: "Charlie Wilson",
    email: "charlie@example.com",
    contact: "+1-555-7890",
    total: "299.99",
    status: "Cancelled",
    payment: "Refunded",
    dueDate: "2025-06-19",
    date: "2025-06-17",
    items: 4,
    productName: "Gaming Keyboard",
    productImg: "https://example.com/images/keyboard.jpg",
  },
];

export const customers = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    phone: "+1 (555) 123-4567",
    location: "New York, NY",
    orders: 12,
    totalSpent: "1,250.00",
    status: "Active",
    joinDate: "2024-01-15",
    avatar: "👤",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "+1 (555) 987-6543",
    location: "Los Angeles, CA",
    orders: 8,
    totalSpent: "890.50",
    status: "Active",
    joinDate: "2024-02-20",
    avatar: "👩",
  },
  {
    id: 3,
    name: "Bob Johnson",
    email: "bob@example.com",
    phone: "+1 (555) 456-7890",
    location: "Chicago, IL",
    orders: 15,
    totalSpent: "2,100.75",
    status: "VIP",
    joinDate: "2023-11-10",
    avatar: "👨",
  },
  {
    id: 4,
    name: "Alice Brown",
    email: "alice@example.com",
    phone: "+1 (555) 321-0987",
    location: "Houston, TX",
    orders: 3,
    totalSpent: "456.25",
    status: "Active",
    joinDate: "2024-05-05",
    avatar: "👩‍💼",
  },
  {
    id: 5,
    name: "Charlie Wilson",
    email: "charlie@example.com",
    phone: "+1 (555) 654-3210",
    location: "Phoenix, AZ",
    orders: 0,
    totalSpent: "0.00",
    status: "Inactive",
    joinDate: "2024-06-01",
    avatar: "🧑",
  },
];
